sudo: false

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "4"
  - "6"
  - "8"
  - "10"

script: npm run coverage-lcov

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
