// Generated by CoffeeScript 1.12.1
'use strict';
var NOT_OPTIMIZED, OPTIMIZED, assert, check, optimize, ref, verify;

assert = require('assert');

optimize = require('../../../lib');

check = optimize.check;

ref = require('../../helpers'), verify = ref.verify, OPTIMIZED = ref.OPTIMIZED, NOT_OPTIMIZED = ref.NOT_OPTIMIZED;

describe('test optimize.check', function() {
  verify({
    name: 'with non-optimized function',
    fn: function() {
      return eval('');
    },
    answer: NOT_OPTIMIZED
  });

  (function() {
    function fnOptimized() {};
    optimize(fnOptimized);
    return verify({
      name: 'with optimized function',
      fn: fnOptimized,
      answer: OPTIMIZED
    });
  })();
});
